/* eslint-disable */
/**
 * Blockchain Proof
 * With the Blockchain Proof API it is easy to prove or disprove existence of data at a certain point in time. Behind the scenes it stores entries using the Factom (bitcoin), Multichain or Ethereum blockchain by means of our generic blockchain API.    The flow is generally as follows:  1. Make sure a configuration is present  2. Register content by uploading a file, some content, or providing a Stream Location from the Storage API. When you upload content you have to tell the API whether the data has already been hashed or not. If not, or when uploading a file or stream location, the API will take care of the hashing  3. Verify content by uploading a file, some content, or providing a Stream Location from the Storage API. When you upload content you have to tell the API whether the data has already been hashed or not. If not, or when uploading a file or stream location, the API will take care of the hashing. You will get back whether the content has been registered previously or not    Full API Documentation: https://docs.sphereon.com/api/blockchain-proof/0.10/html  Interactive testing: A web based test console is available in the Sphereon API Store at https://store.sphereon.com
 *
 * OpenAPI spec version: 0.10
 * Contact: dev@sphereon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['../ApiClient', '../model/SignatureSettings'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./SignatureSettings'));
  } else {
    // Browser globals (root is window)
    if (!root.BlockchainProof) {
      root.BlockchainProof = {};
    }
    root.BlockchainProof.ChainSettings = factory(root.BlockchainProof.ApiClient, root.BlockchainProof.SignatureSettings);
  }
}(this, function(ApiClient, SignatureSettings) {
  'use strict';




  /**
   * The ChainSettings model module.
   * @module ../model/ChainSettings
   * @version 0.10
   */

  /**
   * Constructs a new <code>ChainSettings</code>.
   * Existence ChainSettings. Normally you only supply them once during chain creation or during a settings update. You can also supply them during a content request, but then it is up to you to also supply the correct setting during verify
   * @alias module:../model/ChainSettings
   * @class
   * @param contentRegistrationChainTypes {Array.<module:../model/ChainSettings.ContentRegistrationChainTypesEnum>} A set of content registration chain types. This can be a single proof chain for all hashes, a more powerful chain per hash, or both
   * @param signatureSettings {module:../model/SignatureSettings} Settings that determine how the signature should be registered/verified
   * @param version {module:../model/ChainSettings.VersionEnum} The settings version (only 1 for now)
   */
  var exports = function(contentRegistrationChainTypes, signatureSettings, version) {
    var _this = this;


    _this['contentRegistrationChainTypes'] = contentRegistrationChainTypes;
    _this['signatureSettings'] = signatureSettings;
    _this['version'] = version;

  };

  /**
   * Constructs a <code>ChainSettings</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:../model/ChainSettings} obj Optional instance to populate.
   * @return {module:../model/ChainSettings} The populated <code>ChainSettings</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('singleProofChain')) {
        obj['singleProofChain'] = ApiClient.convertToType(data['singleProofChain'], 'String');
      }
      if (data.hasOwnProperty('contentRegistrationChainTypes')) {
        obj['contentRegistrationChainTypes'] = ApiClient.convertToType(data['contentRegistrationChainTypes'], ['String']);
      }
      if (data.hasOwnProperty('signatureSettings')) {
        obj['signatureSettings'] = SignatureSettings.constructFromObject(data['signatureSettings']);
      }
      if (data.hasOwnProperty('version')) {
        obj['version'] = ApiClient.convertToType(data['version'], 'Number');
      }
      if (data.hasOwnProperty('hashAlgorithm')) {
        obj['hashAlgorithm'] = ApiClient.convertToType(data['hashAlgorithm'], 'String');
      }
    }
    return obj;
  }

  /**
   * The proof chain Id linked to the current configuration. This is a shared proof chain for all registrations/hashes. Only when the single proof chain type has been configured.
   * @member {String} singleProofChain
   */
  exports.prototype['singleProofChain'] = undefined;
  /**
   * A set of content registration chain types. This can be a single proof chain for all hashes, a more powerful chain per hash, or both
   * @member {Array.<module:../model/ChainSettings.ContentRegistrationChainTypesEnum>} contentRegistrationChainTypes
   */
  exports.prototype['contentRegistrationChainTypes'] = undefined;
  /**
   * Settings that determine how the signature should be registered/verified
   * @member {module:../model/SignatureSettings} signatureSettings
   */
  exports.prototype['signatureSettings'] = undefined;
  /**
   * The settings version (only 1 for now)
   * @member {module:../model/ChainSettings.VersionEnum} version
   */
  exports.prototype['version'] = undefined;
  /**
   * The hashing method used for the content. We always return and expect the hash in base64 form
   * @member {module:../model/ChainSettings.HashAlgorithmEnum} hashAlgorithm
   */
  exports.prototype['hashAlgorithm'] = undefined;


  /**
   * Allowed values for the <code>contentRegistrationChainTypes</code> property.
   * @enum {String}
   * @readonly
   */
  exports.ContentRegistrationChainTypesEnum = {
    /**
     * value: "PER_HASH_PROOF_CHAIN"
     * @const
     */
    "PER_HASH_PROOF_CHAIN": "PER_HASH_PROOF_CHAIN",
    /**
     * value: "SINGLE_PROOF_CHAIN"
     * @const
     */
    "SINGLE_PROOF_CHAIN": "SINGLE_PROOF_CHAIN"  };

  /**
   * Allowed values for the <code>version</code> property.
   * @enum {Number}
   * @readonly
   */
  exports.VersionEnum = {
    /**
     * value: 1
     * @const
     */
    "1": 1  };

  /**
   * Allowed values for the <code>hashAlgorithm</code> property.
   * @enum {String}
   * @readonly
   */
  exports.HashAlgorithmEnum = {
    /**
     * value: "SHA_256"
     * @const
     */
    "256": "SHA_256",
    /**
     * value: "SHA_512"
     * @const
     */
    "512": "SHA_512"  };


  return exports;
}));


