/* eslint-disable */
/**
 * Blockchain Proof
 * With the Blockchain Proof API it is easy to prove or disprove existence of data at a certain point in time. Behind the scenes it stores entries using the Factom (bitcoin), Multichain or Ethereum blockchain by means of our generic blockchain API.    The flow is generally as follows:  1. Make sure a configuration is present  2. Register content by uploading a file, some content, or providing a Stream Location from the Storage API. When you upload content you have to tell the API whether the data has already been hashed or not. If not, or when uploading a file or stream location, the API will take care of the hashing  3. Verify content by uploading a file, some content, or providing a Stream Location from the Storage API. When you upload content you have to tell the API whether the data has already been hashed or not. If not, or when uploading a file or stream location, the API will take care of the hashing. You will get back whether the content has been registered previously or not    Full API Documentation: https://docs.sphereon.com/api/blockchain-proof/0.10/html  Interactive testing: A web based test console is available in the Sphereon API Store at https://store.sphereon.com
 *
 * OpenAPI spec version: 0.10
 * Contact: dev@sphereon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['../ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.BlockchainProof) {
      root.BlockchainProof = {};
    }
    root.BlockchainProof.CommittedEntry = factory(root.BlockchainProof.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The CommittedEntry model module.
   * @module ../model/CommittedEntry
   * @version 0.10
   */

  /**
   * Constructs a new <code>CommittedEntry</code>.
   * Commited Entry
   * @alias module:../model/CommittedEntry
   * @class
   * @param registrationState {module:../model/CommittedEntry.RegistrationStateEnum} The registration state of the entry
   * @param entryId {String} The entry Id for the registration
   */
  var exports = function(registrationState, entryId) {
    var _this = this;




    _this['registrationState'] = registrationState;


    _this['entryId'] = entryId;
  };

  /**
   * Constructs a <code>CommittedEntry</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:../model/CommittedEntry} obj Optional instance to populate.
   * @return {module:../model/CommittedEntry} The populated <code>CommittedEntry</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('registrationTime')) {
        obj['registrationTime'] = ApiClient.convertToType(data['registrationTime'], 'Date');
      }
      if (data.hasOwnProperty('chainId')) {
        obj['chainId'] = ApiClient.convertToType(data['chainId'], 'String');
      }
      if (data.hasOwnProperty('context')) {
        obj['context'] = ApiClient.convertToType(data['context'], 'String');
      }
      if (data.hasOwnProperty('registrationState')) {
        obj['registrationState'] = ApiClient.convertToType(data['registrationState'], 'String');
      }
      if (data.hasOwnProperty('signatureState')) {
        obj['signatureState'] = ApiClient.convertToType(data['signatureState'], 'String');
      }
      if (data.hasOwnProperty('signatureStateMessage')) {
        obj['signatureStateMessage'] = ApiClient.convertToType(data['signatureStateMessage'], 'String');
      }
      if (data.hasOwnProperty('entryId')) {
        obj['entryId'] = ApiClient.convertToType(data['entryId'], 'String');
      }
    }
    return obj;
  }

  /**
   * The registration time of the entry. Only when registration has occurred ofcourse
   * @member {Date} registrationTime
   */
  exports.prototype['registrationTime'] = undefined;
  /**
   * Chain Id
   * @member {String} chainId
   */
  exports.prototype['chainId'] = undefined;
  /**
   * The context
   * @member {String} context
   */
  exports.prototype['context'] = undefined;
  /**
   * The registration state of the entry
   * @member {module:../model/CommittedEntry.RegistrationStateEnum} registrationState
   */
  exports.prototype['registrationState'] = undefined;
  /**
   * This is the signature state.
   * @member {module:../model/CommittedEntry.SignatureStateEnum} signatureState
   */
  exports.prototype['signatureState'] = undefined;
  /**
   * This is a message describing the signature state.
   * @member {String} signatureStateMessage
   */
  exports.prototype['signatureStateMessage'] = undefined;
  /**
   * The entry Id for the registration
   * @member {String} entryId
   */
  exports.prototype['entryId'] = undefined;


  /**
   * Allowed values for the <code>registrationState</code> property.
   * @enum {String}
   * @readonly
   */
  exports.RegistrationStateEnum = {
    /**
     * value: "NOT_REGISTERED"
     * @const
     */
    "NOT_REGISTERED": "NOT_REGISTERED",
    /**
     * value: "PENDING"
     * @const
     */
    "PENDING": "PENDING",
    /**
     * value: "REGISTERED"
     * @const
     */
    "REGISTERED": "REGISTERED"  };

  /**
   * Allowed values for the <code>signatureState</code> property.
   * @enum {String}
   * @readonly
   */
  exports.SignatureStateEnum = {
    /**
     * value: "NOT_FOUND"
     * @const
     */
    "NOT_FOUND": "NOT_FOUND",
    /**
     * value: "UNSIGNED"
     * @const
     */
    "UNSIGNED": "UNSIGNED",
    /**
     * value: "INVALID"
     * @const
     */
    "INVALID": "INVALID",
    /**
     * value: "VERIFIED"
     * @const
     */
    "VERIFIED": "VERIFIED"  };


  return exports;
}));


