/* eslint-disable */
/**
 * Blockchain Proof
 * With the Blockchain Proof API it is easy to prove or disprove existence of data at a certain point in time. Behind the scenes it stores entries using the Factom (bitcoin), Multichain or Ethereum blockchain by means of our generic blockchain API.    The flow is generally as follows:  1. Make sure a configuration is present  2. Register content by uploading a file, some content, or providing a Stream Location from the Storage API. When you upload content you have to tell the API whether the data has already been hashed or not. If not, or when uploading a file or stream location, the API will take care of the hashing  3. Verify content by uploading a file, some content, or providing a Stream Location from the Storage API. When you upload content you have to tell the API whether the data has already been hashed or not. If not, or when uploading a file or stream location, the API will take care of the hashing. You will get back whether the content has been registered previously or not    Full API Documentation: https://docs.sphereon.com/api/blockchain-proof/0.10/html  Interactive testing: A web based test console is available in the Sphereon API Store at https://store.sphereon.com
 *
 * OpenAPI spec version: 0.10
 * Contact: dev@sphereon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['../ApiClient', '../model/SignatureSettings'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./SignatureSettings'));
  } else {
    // Browser globals (root is window)
    if (!root.BlockchainProof) {
      root.BlockchainProof = {};
    }
    root.BlockchainProof.ContentRequest = factory(root.BlockchainProof.ApiClient, root.BlockchainProof.SignatureSettings);
  }
}(this, function(ApiClient, SignatureSettings) {
  'use strict';




  /**
   * The ContentRequest model module.
   * @module ../model/ContentRequest
   * @version 0.10
   */

  /**
   * Constructs a new <code>ContentRequest</code>.
   * Content existence request
   * @alias module:../model/ContentRequest
   * @class
   * @param hashProvider {module:../model/ContentRequest.HashProviderEnum} When CLIENT is supplied the content should already have been hashed by you. When SERVER is supplied we will hash the content. Please note that we do not validate the hash when you supply it
   * @param content {Blob} The content to register in base64.
   */
  var exports = function(hashProvider, content) {
    var _this = this;


    _this['hashProvider'] = hashProvider;

    _this['content'] = content;
  };

  /**
   * Constructs a <code>ContentRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:../model/ContentRequest} obj Optional instance to populate.
   * @return {module:../model/ContentRequest} The populated <code>ContentRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('fileName')) {
        obj['fileName'] = ApiClient.convertToType(data['fileName'], 'String');
      }
      if (data.hasOwnProperty('hashProvider')) {
        obj['hashProvider'] = ApiClient.convertToType(data['hashProvider'], 'String');
      }
      if (data.hasOwnProperty('signatureSettings')) {
        obj['signatureSettings'] = SignatureSettings.constructFromObject(data['signatureSettings']);
      }
      if (data.hasOwnProperty('content')) {
        obj['content'] = ApiClient.convertToType(data['content'], 'Blob');
      }
    }
    return obj;
  }

  /**
   * Optional fileName. Used when content extraction is enabled and SERVER hashing is being used. This allows better content extraction of binary file formats like Office files. Do not use when using CLIENT as hashProvider
   * @member {String} fileName
   */
  exports.prototype['fileName'] = undefined;
  /**
   * When CLIENT is supplied the content should already have been hashed by you. When SERVER is supplied we will hash the content. Please note that we do not validate the hash when you supply it
   * @member {module:../model/ContentRequest.HashProviderEnum} hashProvider
   */
  exports.prototype['hashProvider'] = undefined;
  /**
   * Optional signature settings like signature type
   * @member {module:../model/SignatureSettings} signatureSettings
   */
  exports.prototype['signatureSettings'] = undefined;
  /**
   * The content to register in base64.
   * @member {Blob} content
   */
  exports.prototype['content'] = undefined;


  /**
   * Allowed values for the <code>hashProvider</code> property.
   * @enum {String}
   * @readonly
   */
  exports.HashProviderEnum = {
    /**
     * value: "SERVER"
     * @const
     */
    "SERVER": "SERVER",
    /**
     * value: "CLIENT"
     * @const
     */
    "CLIENT": "CLIENT"  };


  return exports;
}));


