/* eslint-disable */
/**
 * Blockchain Proof
 * With the Blockchain Proof API it is easy to prove or disprove existence of data at a certain point in time. Behind the scenes it stores entries using the Factom (bitcoin), Multichain or Ethereum blockchain by means of our generic blockchain API.    The flow is generally as follows:  1. Make sure a configuration is present  2. Register content by uploading a file, some content, or providing a Stream Location from the Storage API. When you upload content you have to tell the API whether the data has already been hashed or not. If not, or when uploading a file or stream location, the API will take care of the hashing  3. Verify content by uploading a file, some content, or providing a Stream Location from the Storage API. When you upload content you have to tell the API whether the data has already been hashed or not. If not, or when uploading a file or stream location, the API will take care of the hashing. You will get back whether the content has been registered previously or not    Full API Documentation: https://docs.sphereon.com/api/blockchain-proof/0.10/html  Interactive testing: A web based test console is available in the Sphereon API Store at https://store.sphereon.com
 *
 * OpenAPI spec version: 0.10
 * Contact: dev@sphereon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['../ApiClient', '../model/ChainSettings', '../model/ContentExtractionSettings'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ChainSettings'), require('./ContentExtractionSettings'));
  } else {
    // Browser globals (root is window)
    if (!root.BlockchainProof) {
      root.BlockchainProof = {};
    }
    root.BlockchainProof.CreateConfigurationRequest = factory(root.BlockchainProof.ApiClient, root.BlockchainProof.ChainSettings, root.BlockchainProof.ContentExtractionSettings);
  }
}(this, function(ApiClient, ChainSettings, ContentExtractionSettings) {
  'use strict';




  /**
   * The CreateConfigurationRequest model module.
   * @module ../model/CreateConfigurationRequest
   * @version 0.10
   */

  /**
   * Constructs a new <code>CreateConfigurationRequest</code>.
   * Create a context configuration
   * @alias module:../model/CreateConfigurationRequest
   * @class
   * @param initialSettings {module:../model/ChainSettings} The initial context settings.
   * @param context {String} The Easy Blockchain API context. This has to be a context you created or a public context
   * @param name {String} The configuration name.
   * @param accessMode {module:../model/CreateConfigurationRequest.AccessModeEnum} The access mode for this configuration. Public means accessible to other tenants of the API as well. Currently public is only allowed for Sphereon itself
   */
  var exports = function(initialSettings, context, name, accessMode) {
    var _this = this;

    _this['initialSettings'] = initialSettings;
    _this['context'] = context;
    _this['name'] = name;

    _this['accessMode'] = accessMode;
  };

  /**
   * Constructs a <code>CreateConfigurationRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:../model/CreateConfigurationRequest} obj Optional instance to populate.
   * @return {module:../model/CreateConfigurationRequest} The populated <code>CreateConfigurationRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('initialSettings')) {
        obj['initialSettings'] = ChainSettings.constructFromObject(data['initialSettings']);
      }
      if (data.hasOwnProperty('context')) {
        obj['context'] = ApiClient.convertToType(data['context'], 'String');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('contentExtractionSettings')) {
        obj['contentExtractionSettings'] = ContentExtractionSettings.constructFromObject(data['contentExtractionSettings']);
      }
      if (data.hasOwnProperty('accessMode')) {
        obj['accessMode'] = ApiClient.convertToType(data['accessMode'], 'String');
      }
    }
    return obj;
  }

  /**
   * The initial context settings.
   * @member {module:../model/ChainSettings} initialSettings
   */
  exports.prototype['initialSettings'] = undefined;
  /**
   * The Easy Blockchain API context. This has to be a context you created or a public context
   * @member {String} context
   */
  exports.prototype['context'] = undefined;
  /**
   * The configuration name.
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {module:../model/ContentExtractionSettings} contentExtractionSettings
   */
  exports.prototype['contentExtractionSettings'] = undefined;
  /**
   * The access mode for this configuration. Public means accessible to other tenants of the API as well. Currently public is only allowed for Sphereon itself
   * @member {module:../model/CreateConfigurationRequest.AccessModeEnum} accessMode
   */
  exports.prototype['accessMode'] = undefined;


  /**
   * Allowed values for the <code>accessMode</code> property.
   * @enum {String}
   * @readonly
   */
  exports.AccessModeEnum = {
    /**
     * value: "PUBLIC"
     * @const
     */
    "PUBLIC": "PUBLIC",
    /**
     * value: "PRIVATE"
     * @const
     */
    "PRIVATE": "PRIVATE"  };


  return exports;
}));


